### ISSUE TITLE
Builder Command

### ISSUE THREAD

**Issue by HDVinnie** [austintoddj/laravel-zoom#30]
```
Commands

A builder:resource command will help generate the underlying structure needed for extending your application. Run the following command to create an entity, interface and repository for a specific class:

php artisan builder:resource {class} {namespace} {table}
```

Would be helpful if there was option for it to also make a migration file no?

**Comment by austintoddj** [comment]
That would make sense to add here. Feel free to submit a PR if you'd like!

**Comment by austintoddj** [comment]
Giving this some more thought, I'd like to keep the migration portion out of it, since there is more ambiguity in either the naming convention of a migration or the fact that we may want a resource without writing any database changes. Thanks for the idea though!
